# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  projectFolder: "src"
  buildOutputFolder: "build"

steps:
  - script: |
      pushd $(projectFolder) && npm install && popd
      pushd $(projectFolder) && npm run build && popd

  - task: CopyFiles@2
    inputs:
      sourceFolder: "$(buildOutputFolder)"
      contents: "**/*"
      targetFolder: "$(Build.ArtifactStagingDirectory)"
      cleanTargetFolder: true

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: $(Build.ArtifactStagingDirectory)
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
      includeRootFolder: false

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
