# Node.js React Web App to Linux on Azure
# Build a Node.js React app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascriptttyy

trigger:
  - master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: "71d18f85-881b-44b7-8605-cc3ad719d866"

  # Web app name
  webAppName: "ReservationsRocoto"

  # Environment name
  environmentName: "ReservationsRocoto"

  # Agent VM image name
  vmImageName: "ubuntu-latest"

steps:
  - task: ArchiveFiles@2
    displayName: "Archive files"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      replaceExistingArchive: true

  - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    artifact: drop

  - task: AzureRmWebAppDeployment@4
    displayName: "Azure App Service Deploy: ReservationsRocoto"
    inputs:
      azureSubscription: $(azureSubscription)
      appType: webAppLinux
      WebAppName: $(webAppName)
      packageForLinux: "$(Pipeline.Workspace)/drop/$(Build.BuildId).zip"
      RuntimeStack: "NODE|10.10"
      StartupCommand: "npm run start"
      ScriptType: "Inline Script"
      InlineScript: |
        npm install
        npm run build --if-present
